<?php
function get_logins()
{
    return array(
        //Paswoord = "paswoord1"
        'louis' => array('Louis', 'Verleysen', '11d937dd708d40ec077d26d66f6c4c98', '24/12/1944'),
        //Paswoord = "paswoord2"
        'tincidunt' => array('Ciara', 'Buchanan', 'de8ec5047540099dc9c8f854b494bd74', '05/14/1999'),
        //Paswoord = "paswoord3"
        'vitae' => array('Xavier', 'Lucas', '107db61cae14fdbe588a3f996655c100', '08/11/1980'),
        //Paswoord = "paswoord4"
        'lectus' => array('Hannah', 'Newton', 'a5f543df0b4882422f6742dcff93dae5', '12/05/1968'),
        //Paswoord = "paswoord5"
        'tristique' => array('Alexa', 'Phelps', '63c04e6274daa5a25939ae46adcee976', '02/19/1948'),
        //Paswoord = "paswoord6"
        'dignissim' => array('Beck', 'Holt', 'bdf6f2a648009b4bc5ecae20e866a70f', '10/16/1987'),
        //Paswoord = "paswoord7"
        'et' => array('Xantha', 'Matthews', '7dd619d5d2161cecb553ad4ccafcb8d4', '14/07/2000'),
        //Paswoord = "paswoord8"
        'nunc' => array('Raphael', 'Goodwin', 'faf4e043d0a3d751e19f617bd36be4c9', '02/18/1963'),
        //Paswoord = "paswoord9"
        'nisi' => array('Rudyard', 'Poole', '9827e1fc8016356af12943a1abef01f3', '20/07/1949'),
        //Paswoord = "paswoord10"
        'lacus' => array('Zane', 'Rowland', '2bdb33424455889ffa83e55aaba60793', '10/23/1981'),
    );
}
